apiVersion: batch/v1
kind: Job
metadata:
  name: 5g-blueprint-{{ now | unixEpoch }}
  namespace: {{ .Release.Namespace }}
spec:
  # keep the job for 2 hours after successful completion
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      labels:
        app: 5g-blueprint-{{ now | unixEpoch }}
    spec:
    {{- if .Values.imagePullSecrets.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
    {{- end }}    
      initContainers:
      - name: init-setup
        image: debian:stable-slim
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Downloading 5G Blueprint file..."
            curl -sSL -o /data/5gblueprint-edge.json https://raw.githubusercontent.com/5GSEC/5g-blueprint-controls/refs/heads/main/5gblueprint.json
            curl -sSL -o /data/5gblueprint-core.json https://raw.githubusercontent.com/5GSEC/5g-blueprint-controls/refs/heads/main/5gblueprint-core.json
            echo "Running Kubescape scan..."
      - name: job-kubescape-container
        image: "{{ .Values.kubescape.image.repository }}:{{ .Values.kubescape.image.tag }}"
        # scan framework 5Gblueprint-CORE --kube-context core-admin@core --use-from ~/regolibrary/release/5gblueprint-core.json  --exceptions ~/excep2.json --format html --output core-after.html
        args: ["scan", "framework", "5GBlueprint", "--format", "json", "--use-from", "/data/5gblueprint-$(CLUSTER_NAME).json", "--output", "/data/report.json", "--cluster-name=$(CLUSTER_NAME)"]
        env:
         - name: CLUSTER_NAME
           value: {{ .Values.accuknox.clusterName }}
        volumeMounts:
        - name: datapath
          mountPath: /data
      

      containers:
        - image: "{{ .Values.accuknoxJob.image.repository }}:{{ .Values.accuknoxJob.image.tag }}"
          name: artifact-api-container
          command:
            - '/bin/sh'
            - '/script/augment-and-push-results.sh'
          env:
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: AUTH_TOKEN
                  {{- if (.Values.accuknox.secretName | empty) }}
                  name: 5g-blueprint-auth-token
                  {{- else }}
                  name: {{ .Values.accuknox.secretName }}
                  {{- end }}
            - name: URL
              value: {{ .Values.accuknox.URL }}
            - name: TENANT_ID
              value: {{ .Values.accuknox.tenantID | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.accuknox.clusterName }}
            - name: CLUSTER_ID
              value: {{ .Values.accuknox.clusterID | quote }}
            - name: LABEL_NAME
              value: {{ .Values.accuknox.label }}
          volumeMounts:
            - mountPath: /data
              name: datapath
            - mountPath: /script
              name: scriptpath
      volumes:
        - name: datapath
          emptyDir: {}
        - name: scriptpath
          configMap:
            name: 5g-blueprint-script-configmap
      restartPolicy: OnFailure
      serviceAccount: 5g-blueprint-service-account
